# -*- coding: utf-8 -*-
"""IST652_Week1_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/amroth917/8ed5b43421465acd269d38644a8defbb/ist652_week1_4.ipynb

Allison Roth
July 23, 2019
Week 1
Activity 1.4
Boolean and Conditional Statements
"""

num1 = 0.95

if num1 >= 0.9:
  print('Enter Score', num1, 'Grade: A')
else:
    if num1 >=0.8:
      print('Enter Score', num1, 'Grade: B')
    else:
      if num1 >=0.7:
        print('Enter Score', num1, 'Grade: C')
      else:
        if num1 >=0.6:
          print('Enter Score', num1, 'Grade: D')
        else:
            if num1 < 0.6:
              print('Enter Score', num1, 'Grade: F')
            else:
              print('Enter Score', num1, 'Bad Score')

num1 = .75

if num1 >= 0.9:
  print('Enter Score', num1, 'Grade: A')
else:
    if num1 >=0.8:
      print('Enter Score', num1, 'Grade: B')
    else:
      if num1 >=0.7:
        print('Enter Score', num1, 'Grade: C')
      else:
        if num1 >=0.6:
          print('Enter Score', num1, 'Grade: D')
        else:
            if num1 < 0.6:
              print('Enter Score', num1, 'Grade: F')
            else:
              print('Enter Score', num1, 'Bad Score')

num1 = 0.5

if num1 >= 0.9:
  print('Enter Score', num1, 'Grade: A')
else:
    if num1 >=0.8:
      print('Enter Score', num1, 'Grade: B')
    else:
      if num1 >=0.7:
        print('Enter Score', num1, 'Grade: C')
      else:
        if num1 >=0.6:
          print('Enter Score', num1, 'Grade: D')
        else:
            if num1 < 0.6:
              print('Enter Score', num1, 'Grade: F')
            else:
              print('Enter Score', num1, 'Bad Score')